### ISSUE TITLE
Adding Author to Blog Posts

### ISSUE THREAD

**Issue by MayaGans** [budparr/gohugo-theme-ananke#113]
Hi! I was wondering if it'd be possible to add the blog post author to the top of each post page, possibly automating this? [I found a blog post related to this](https://discourse.gohugo.io/t/how-to-access-site-params-map-with-a-params-variable/348), but because I'm a total n00b I'm not sure how to go about implementing it within the theme or where to add this script within the css. Any tips helpful, and thanks for the wonderful blog layout!

**Comment by budparr** [comment]
Hi @MayaGans You'd want to duplicate this template: https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/_default/single.html into your root layouts directory (so it would be like `/layouts/_default/single.html` instead of `/gohugo-theme-ananke/blob/master/layouts/_default/single.html` and add the code there. Unfortunately, I don't have time to help you with the actual code, but it's definitely doable. People in the forums would be able to help you with that and I'll consider adding authors in a future version of the theme.

**Comment by Beanow** [comment]
I've added a PR above. It's a simple implementation that doesn't go all over the place like lists to add it. However it's there on the blog post itself.

For the website I'm writing for now I believe it's necessary, because part of the site is written from "we" perspective. But blog posts can also be opinion written in "I" form which needs the author for this distinction.
