### ISSUE TITLE
description field in _index.md  or config.toml (override?) 

### ISSUE THREAD

**Issue by dingesista** [budparr/gohugo-theme-ananke#116]
Hello there!

Experimenting with this template, I notice that setting the description in the config.toml does not give the expected result. However, copying _index.md and setting it there does. Is that a bug?

**Comment by budparr** [comment]
Hi, @dingesista Can you tell me where you expect the description to show up that it's not?

**Comment by dingesista** [comment]
in the example  site the config.tom description = "The last theme you'll ever need. Maybe."

That is one of the lines of text on the image on the home page. Turns out, this setting is configured by changing the same line in _index.md in content/_index.md

**Comment by budparr** [comment]
I can see where that would be confusing. The description in the sample config acts as a fallback description in meta tags for pages where there might not be a description that shows up otherwise. Here's an example: https://github.com/gohugoio/hugo/blob/9c1e82085eb07d5b4dcdacbe82d5bafd26e08631/tpl/tplimpl/embedded/templates/opengraph.html#L2

The description you are referring to is designed to come from the page itself. `content/_index.md`is the home page. Make sense?

**Comment by dingesista** [comment]
Thanks!
