### ISSUE TITLE
Hero image not sought or 404

### ISSUE THREAD

**Issue by eidolonic** [budparr/gohugo-theme-ananke#19]
When running in localhost with hugo server, hero image cannot be found and sometimes isn't even looked for. 

Have tried:

* Specifying in site config.toml featured_image -- Does not appear to be respected at all; Network tab shows no attempt to find file
* Specifying in content/_index.md front matter featured_image: 'static/images/file.jpg' -- Site tries to pull from //localhost:1313/static/images/file.jpg but always 404s.
* Copying the specified hero image to (site root)/static/images/file.jpg, (site root)/content/static/images/file.jpg and same structures inside theme folder.

Did I fall asleep in class and just miss something? 😴

**Comment by budparr** [comment]
Thank you, @eidolonic It's very likely something I did trying to get the URLs to work on any instance, including where the install is in a nested folder. I'll have a look tonight.

**Comment by budparr** [comment]
Hey, @eidolonic 

> Specifying in site config.toml featured_image -- Does not appear to be respected at all; Network tab shows no attempt to find file

At some point I changed this to not use a config default because I felt like the behavior should be not to have anything if you didn't have an image on the page. If you want the default from the config, I can show you how to do that `{{ $featured_image := .Params.featured_image | default .Site.Params.featured_image }} `

> Specifying in content/_index.md front matter featured_image: 'static/images/file.jpg' -- Site tries to pull from //localhost:1313/static/images/file.jpg but always 404s.

The reference should not include `static`

> Copying the specified hero image to (site root)/static/images/file.jpg, (site root)/content/static/images/file.jpg and same structures inside theme folder.

"(site root)/static/images/file.jpg" looks right to me. 

I tested the theme with the sample content and it seems to work okay. If you want to post your repo, I'm happy to have a look.

**Comment by eidolonic** [comment]
@budparr Thanks for your detailed response and sorry for squirreling you on a non-issue. Simply removing the `static` portion of the front matter reference fixed the problem. Thought I had tried that, but clearly not. 😎 Thanks for a killer theme.

**Comment by budparr** [comment]
Awesome! Glad to hear you got it figured out.
