### ISSUE TITLE
See if HLJS can work on generic (non-language specific) code blocks

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo-theme-ananke#23]
Currently HLJS is cued off of the class `language-html` or other appropriate language. Code blocks only get that class if they're wrapped in a short-code, and handling of the shortcode is inconsistent through the docs, leaving many left without highlight. 

So either we need to find a way to apply hljs to generic code that doesn't have that class or apply the shortcode uniformly to the code.

cc @digitalcraftsman @rdwatters

https://github.com/budparr/gohugo-theme/issues/13#issuecomment-298175677

**Comment by rdwatters** [comment]
The language declaration doesn't require the shortcode. Hugo (Blackfriday) can take care of triple back ticks, which is all HLJS should need. If it's inconsistent, it just means I missed a few items :smile: The current site uses only the indented syntax (with no language declaration, if I recall), and things are still being highlighted. I'll add this to my list of cleanup this weekend; so, I'll standardize all the code blocks (some of them don't use the shortcode intentionally, since they don't benefit from a copy button, download button, or same file/file path), and also remove all the opinionated classes, IDs, etc....

**Comment by budparr** [comment]
Alright. So I may have been too aggressive with stripping out styles for things that were not Hugo. I see, too that there's Hugo stuff that is `language-html` as well `language-golang` which, the latter, I didn't account for.

**Comment by budparr** [comment]
> since they don't benefit from a copy button, download button, or same file/file path),

Yeah, that makes sense. So things that don't need those features, shouldn't be wrapped in the shortcode, therefore I need to account for them in my styling. I'll take another look. 

and, as you can see here I stripped out everything. https://github.com/budparr/gohugo-theme/blob/master/src/css/_hljs.css

But as far as I understood, HLJS is language specific, but I'll see if I can dig up something, if it's not just handled in the stylesheet.

JS:
https://github.com/budparr/gohugo-theme/blob/master/src/js/hljs.js
