### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by RicardoDanielGonzalez** [budparr/gohugo-theme-ananke#72]
Hi @budparr!
**First of all, many thanks for developing Ananke!**
I'm not a developer, just a pretty beginner with Hugo, and I was wondering if you are considering comments deployment in your theme. I've tried to figure out how reading Hugo's documentation, but I can't solve it.
Thanks again!
Best regards!

**Comment by budparr** [comment]
Hey, @RicardoDanielGonzalez That shouldn't be a problem. Thanks for the suggestion.

**Comment by redapemusic35** [comment]
I love this theme. I have just started using this theme and I am really happy with the results of my webpage. I was wondering though if you have added the ability to add comments? I am a novice so please forgive me if you have already.

**Comment by Avizini** [comment]
@redapemusic35 Afaik No, currently there is no option to add comments but you can embed disqus or any other system if you want. Staticman is another option, if you are unable to do it then ping me I'll guide you through this.

**Comment by budparr** [comment]
I'm thinking of using Staticman, though I'm not sure if there are too many moving parts to that to package as a theme. My problem with DISQUS is that there are privacy issues. Perhaps if I include some instructions on setting up DISQUS yourselves. It would not be hard, I don't think.

**Comment by Avizini** [comment]
@redapemusic35 I am not sharing exact instructions, nor I have a system to test this. So you might have to do some work yourself.

First goto Disqus and make an account, follow their instructions. Then they will ask you for the cms you are using, you will see an option saying universal code.

Yeah, copy that and keep it. Now open your theme, there you will see partials go there and search every file for .{content} 

Dont copy and paste, look it with your eyes because I am not sure if that is the syntax. I am also not sure of it is in the partials (i think single.html) folder. After you find it, paste the code below it and look at your website. 

You will see a bad but working implementation of  disqus. Now you might want to make another file to make it look good. Make another file in the same folder called comment.html and paste the code there, now goto the file where you got .{content stuff , link that partial there. 

Below you will see.{footer or something like that, copy it and change footer to comment and paste it below .content

Again look at your site, it will look the same but me made it tidy. Now if it looks good then leave or else you need to learn some html and css yourself and.style it.


Again, I have not tested nor I can. I have also not seen hugo since weeks, so dunno about file structure and stuff. 

Share the site once its done :)

**Comment by Avizini** [comment]
Here you go, I have not worked with themes since months so I don't know if this will work. Go to layouts/_default/single.html and stay there.

Now open disqus account and follow their instructions, when they ask you to chose a cms (wordpress,etc..) . there chose universal code and copy it somewhere, now close that tab and back to theme folder. 

```
<div class="nested-copy-line-height lh-copy f4 nested-links nested-img mid-gray">
        {{ .Content }}
</div>
```

Below </div> paste your code and look at the blog, everything looks good..? You might have a dirty but working comments system. Now go to layouts/partials/ and over there make a file called comment.html

Now remove the code from single.html and paste it on comment.html, we have to link comment.html to single.html

Goto single.html and paste this below {{{. Content}} </div> .

``
 {{ partial "comment.html" . }}  //Paste this
``

You will not have a tidy work, if the embed doesn't look good then you might want to style it.

**Comment by budparr** [comment]
Okay everyone, you can now add comments by adding your `disqusShortname` to your config file.

**Comment by melroy89** [comment]
Just a heads up, this behavior is now changed with: https://github.com/theNewDynamic/gohugo-theme-ananke/commit/91df000ca82769a7578df81fa142d1a18e446bc0
