### ISSUE TITLE
Configuring Menu Items

### ISSUE THREAD

**Issue by innomadic** [budparr/gohugo-theme-ananke#82]
I imagine this is a general question for Hugo and not just for this theme, but I am trying out Hugo for the first time and am trying to use this theme.  In the demo page I see "About" "Articles" "Contact" but I don't have any menus like that in my site.  How do I configure them?  I have created a section or two, but they don't seem to show on the main index page of my site.  Where can I configure this, or should it be automatically generated somehow?

**Comment by budparr** [comment]
Have a look at the docs on menus: This is what I use on the demo: https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers

and this is the primary doc on creating menus in your content:
 https://gohugo.io/content-management/menus/

Otherwise, yeah, you'll probably get a lot of responses/help in the forums.
Hope that helps!

**Comment by innomadic** [comment]
Thank you, I think I have it working now.
