### ISSUE TITLE
Interest in new features?

### ISSUE THREAD

**Issue by rcoh** [budparr/gohugo-theme-ananke#84]
Hello! I've been using this theme on my personal blog, https://rcoh.me and it's been great. Along the way I've added some features that I'm happy to bring upstream of you're interested:
* Google Analytics events triggered by social link clicks
* Improved "recent posts" sidebar that shows posts with the same tags
* MathJax support for posts

**Comment by budparr** [comment]
Hey, @rcoh I'm definitely interested. Here are some specific thoughts and I welcome yours. One goal to keep in mind (something that I've learned doing a theme) is to not make things too complicated or specific.

- Google Analytics. I'm not very satisfied with the internal Hugo GA, but was considering leaving it as a simple-base case. I think the best thing to do would be to make it simpler to swap out for a custom GA. 

- I'm intending to improve the sidebar, both from a design perspective (make it more stable in size), and the content within it, because the current set up is not very efficient for build-times. Definitely welcome your contribution for the content bit. 

- I don't know what that entails. It something that can be turned off and on, does it impact build times?

Thank you. I really appreciate this!

**Comment by rcoh** [comment]
* it uses the stock ga template, but invokes an onClick function in the
social outgoing links
* Yeah I remember doing a bunch of work to get the sidebar a good width. It
was pretty hacky so I'll let you do that right but I'll send you the new
partial for content
* Yeah it can be opt in. It's a JS lib that loads in the footer + some
custom JS and css that make it work with Hugo / Markdown. Easy to template
it out when not enabled

**Comment by budparr** [comment]
Hey, @rcoh I've added some changes, including a recent posts sidebar (using Hugo's native related content) and fixed the flex item. I don't think this will break any of your changes since I imagine you made them in your root layout folder, but if not, you may want to test first.

I'm going to close this for now. Always happy to have new ideas/PRs.

Thanks!
