### ISSUE TITLE
option for mp4 for featured_image

### ISSUE THREAD

**Issue by willwade** [budparr/gohugo-theme-ananke#88]
ie https://css-tricks.com/should-i-use-a-video-as-a-background/

**Comment by budparr** [comment]
Hey, @willwade I think this is something that, having done that sort of thing, is edge-case enough that it would be easier just for a user to duplicate the hero template into their layouts folder to accomplish that. I need to keep the scope of this theme, in particular, focused, because the Hugo site sends possibly new users here.

**Comment by willwade** [comment]
Yeah. That’s totally fair enough. (I’m partially popping it here in case
anyone had done what you’ve said so I can copy and paste! Ie. I’m being
lazy! ). Thanks for the great theme :)

**Comment by Altonss** [comment]
> think this is something that, having done that sort of thing, is edge-case enough that it would be easier just for a user to duplicate the hero template into their layouts folder to accomplish that.

Thanks for the trick @budparr, but as I'm new to hugo, what do you mean exactly by "duplicate the here template into their layouts folder to accomplish that?

**Comment by budparr** [comment]
Hi @Altonss If you take any template from the theme and make a copy of it in your site's layouts folder (using the same path structure), it will overwrite the theme's template:

`theme/gohugo-theme-ananke/layouts/partials/template.html`

to:
`/layouts/partials/template.html`
